classDiagram
    class ExplanationStudyBlockContent

    class Scene {
        +duration: number
    }

    class `*Slide*` {
        +startTime: number
    }

    class RawSlide {
    }

    class `*SlideTemplate*` {}

    class Column {
        <<enumeration>>
        First
        Second
        Third
    }

    class VideoComponent {
        +startTime: number
        +column: Column
    }

    class Audio {
        +url: string
    }

    class Caption {
        +text: string
        +startMs: number
        +endMs: number
    }

    ExplanationStudyBlockContent "1" *-- "1..*" Scene
    Scene "1" *-- "1..*" `*Slide*`

    `*Slide*` <|-- RawSlide
    `*Slide*` <|-- `*SlideTemplate*`

    RawSlide "1" *-- "1..*" VideoComponent
    VideoComponent --> Column

    Scene "1" --> "0..1" Audio
    Audio "1" *-- "0..*" Caption
